import pytest

# fmt: on
@pytest.fixture(scope = "session")
def real_django_data():
    # fmt: off
    return {
        'vulns': [
            {'id': 'GHSA-2gwj-7jmv-h26r', 'summary': 'SQL Injection in Django', 'details': 'An issue was discovered in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. QuerySet.annotate(), aggregate(), and extra() methods are subject to SQL injection in column aliases via a crafted dictionary (with dictionary expansion) as the passed **kwargs.', 'aliases': ['CVE-2022-28346'], 'modified': '2022-06-15T20:25:18.040653Z', 'published': '2022-04-13T00:00:33Z', 'database_specific': {'severity': 'CRITICAL', 'github_reviewed': True, 'cwe_ids': ['CWE-89']}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2022-28346'}, {'type': 'WEB', 'url': 'https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/4.0/releases/security/'}, {'type': 'ADVISORY', 'url': 'https://github.com/advisories/GHSA-2gwj-7jmv-h26r'}, {'type': 'WEB', 'url': 'https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-190.yaml'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://lists.debian.org/debian-lts-announce/2022/04/msg00013.html'}, {'type': 'WEB', 'url': 'https://security.netapp.com/advisory/ntap-20220609-0002/'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2022/apr/11/security-releases/'}, {'type': 'WEB', 'url': 'http://www.openwall.com/lists/oss-security/2022/04/11/1'}, {'type': 'PACKAGE', 'url': 'https://github.com/django/django'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '2.2'}, {'fixed': '2.2.28'}]}], 'versions': ['2.2', '2.2.1', '2.2.10', '2.2.11', '2.2.12', '2.2.13', '2.2.14', '2.2.15', '2.2.16', '2.2.17', '2.2.18', '2.2.19', '2.2.2', '2.2.20', '2.2.21', '2.2.22', '2.2.23', '2.2.24', '2.2.25', '2.2.26', '2.2.27', '2.2.3', '2.2.4', '2.2.5', '2.2.6', '2.2.7', '2.2.8', '2.2.9'], 'ecosystem_specific': {'affected_functions': ['django.db.models.QuerySet.annotate', 'django.db.models.QuerySet.aggregate', 'django.db.models.QuerySet.extra']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/04/GHSA-2gwj-7jmv-h26r/GHSA-2gwj-7jmv-h26r.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2'}, {'fixed': '3.2.13'}]}], 'versions': ['3.2', '3.2.1', '3.2.10', '3.2.11', '3.2.12', '3.2.2', '3.2.3', '3.2.4', '3.2.5', '3.2.6', '3.2.7', '3.2.8', '3.2.9'], 'ecosystem_specific': {'affected_functions': ['django.db.models.QuerySet.annotate', 'django.db.models.QuerySet.aggregate', 'django.db.models.QuerySet.extra']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/04/GHSA-2gwj-7jmv-h26r/GHSA-2gwj-7jmv-h26r.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '4.0'}, {'fixed': '4.0.4'}]}], 'versions': ['4.0', '4.0.1', '4.0.2', '4.0.3'], 'ecosystem_specific': {'affected_functions': ['django.db.models.QuerySet.annotate', 'django.db.models.QuerySet.aggregate', 'django.db.models.QuerySet.extra']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/04/GHSA-2gwj-7jmv-h26r/GHSA-2gwj-7jmv-h26r.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'}]},
            {'id': 'GHSA-53qw-q765-4fww', 'summary': 'Denial-of-service in Django', 'details': 'An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.', 'aliases': ['CVE-2021-45115'], 'modified': '2022-06-10T02:15:06.712642Z', 'published': '2022-01-12T19:20:53Z', 'database_specific': {'github_reviewed': True, 'cwe_ids': ['CWE-400'], 'severity': 'HIGH'}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2021-45115'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/4.0/releases/security/'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/'}, {'type': 'WEB', 'url': 'https://security.netapp.com/advisory/ntap-20220121-0005/'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2022/jan/04/security-releases/'}, {'type': 'PACKAGE', 'url': 'https://github.com/django/django'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '2.2.0'}, {'fixed': '2.2.26'}]}], 'versions': ['2.2', '2.2.1', '2.2.10', '2.2.11', '2.2.12', '2.2.13', '2.2.14', '2.2.15', '2.2.16', '2.2.17', '2.2.18', '2.2.19', '2.2.2', '2.2.20', '2.2.21', '2.2.22', '2.2.23', '2.2.24', '2.2.25', '2.2.3', '2.2.4', '2.2.5', '2.2.6', '2.2.7', '2.2.8', '2.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-53qw-q765-4fww/GHSA-53qw-q765-4fww.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2.0'}, {'fixed': '3.2.11'}]}], 'versions': ['3.2', '3.2.1', '3.2.10', '3.2.2', '3.2.3', '3.2.4', '3.2.5', '3.2.6', '3.2.7', '3.2.8', '3.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-53qw-q765-4fww/GHSA-53qw-q765-4fww.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '4.0.0'}, {'fixed': '4.0.1'}]}], 'versions': ['4.0'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-53qw-q765-4fww/GHSA-53qw-q765-4fww.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H'}]},
            {'id': 'GHSA-8c5j-9r9f-c6w8', 'summary': 'Information disclosure in Django', 'details': "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. Due to leveraging the Django Template Language's variable resolution logic, the dictsort template filter was potentially vulnerable to information disclosure, or an unintended method call, if passed a suitably crafted key.", 'aliases': ['CVE-2021-45116'], 'modified': '2022-06-10T02:17:40.238273Z', 'published': '2022-01-12T19:21:10Z', 'database_specific': {'severity': 'HIGH', 'github_reviewed': True, 'cwe_ids': ['CWE-668']}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2021-45116'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/4.0/releases/security/'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/'}, {'type': 'WEB', 'url': 'https://security.netapp.com/advisory/ntap-20220121-0005/'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2022/jan/04/security-releases/'}, {'type': 'PACKAGE', 'url': 'https://github.com/django/django'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '2.2.0'}, {'fixed': '2.2.26'}]}], 'versions': ['2.2', '2.2.1', '2.2.10', '2.2.11', '2.2.12', '2.2.13', '2.2.14', '2.2.15', '2.2.16', '2.2.17', '2.2.18', '2.2.19', '2.2.2', '2.2.20', '2.2.21', '2.2.22', '2.2.23', '2.2.24', '2.2.25', '2.2.3', '2.2.4', '2.2.5', '2.2.6', '2.2.7', '2.2.8', '2.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-8c5j-9r9f-c6w8/GHSA-8c5j-9r9f-c6w8.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2.0'}, {'fixed': '3.2.11'}]}], 'versions': ['3.2', '3.2.1', '3.2.10', '3.2.2', '3.2.3', '3.2.4', '3.2.5', '3.2.6', '3.2.7', '3.2.8', '3.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-8c5j-9r9f-c6w8/GHSA-8c5j-9r9f-c6w8.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '4.0.0'}, {'fixed': '4.0.1'}]}], 'versions': ['4.0'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-8c5j-9r9f-c6w8/GHSA-8c5j-9r9f-c6w8.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N'}]},
            {'id': 'GHSA-jrh2-hc4r-7jwx', 'summary': 'Directory-traversal in Django', 'details': 'Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it.', 'aliases': ['CVE-2021-45452'], 'modified': '2022-06-10T02:15:41.813898Z', 'published': '2022-01-12T19:21:04Z', 'database_specific': {'github_reviewed': True, 'severity': 'MODERATE', 'cwe_ids': ['CWE-22']}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2021-45452'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/4.0/releases/security/'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/'}, {'type': 'WEB', 'url': 'https://security.netapp.com/advisory/ntap-20220121-0005/'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2022/jan/04/security-releases/'}, {'type': 'PACKAGE', 'url': 'https://github.com/django/django'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '2.2.0'}, {'fixed': '2.2.26'}]}], 'versions': ['2.2', '2.2.1', '2.2.10', '2.2.11', '2.2.12', '2.2.13', '2.2.14', '2.2.15', '2.2.16', '2.2.17', '2.2.18', '2.2.19', '2.2.2', '2.2.20', '2.2.21', '2.2.22', '2.2.23', '2.2.24', '2.2.25', '2.2.3', '2.2.4', '2.2.5', '2.2.6', '2.2.7', '2.2.8', '2.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-jrh2-hc4r-7jwx/GHSA-jrh2-hc4r-7jwx.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2.0'}, {'fixed': '3.2.11'}]}], 'versions': ['3.2', '3.2.1', '3.2.10', '3.2.2', '3.2.3', '3.2.4', '3.2.5', '3.2.6', '3.2.7', '3.2.8', '3.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-jrh2-hc4r-7jwx/GHSA-jrh2-hc4r-7jwx.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '4.0.0'}, {'fixed': '4.0.1'}]}], 'versions': ['4.0'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/01/GHSA-jrh2-hc4r-7jwx/GHSA-jrh2-hc4r-7jwx.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N'}]},
            {'id': 'GHSA-qm57-vhq3-3fwf', 'summary': 'Header injection possible in Django', 'details': 'In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers.', 'aliases': ['CVE-2021-32052'], 'modified': '2022-06-10T02:13:49.039665Z', 'published': '2021-06-09T17:14:51Z', 'database_specific': {'cwe_ids': ['CWE-79', 'CWE-88'], 'severity': 'MODERATE', 'github_reviewed': True}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2021-32052'}, {'type': 'WEB', 'url': 'https://github.com/django/django/commit/e1e81aa1c4427411e3c68facdd761229ffea6f6f'}, {'type': 'WEB', 'url': 'https://bugzilla.redhat.com/show_bug.cgi?id=1944801'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/3.2/releases/security/'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE/'}, {'type': 'WEB', 'url': 'https://security.netapp.com/advisory/ntap-20210611-0002/'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2021/may/06/security-releases/'}, {'type': 'WEB', 'url': 'http://www.openwall.com/lists/oss-security/2021/05/06/1'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '2.2.0'}, {'fixed': '2.2.22'}]}], 'versions': ['2.2', '2.2.1', '2.2.10', '2.2.11', '2.2.12', '2.2.13', '2.2.14', '2.2.15', '2.2.16', '2.2.17', '2.2.18', '2.2.19', '2.2.2', '2.2.20', '2.2.21', '2.2.3', '2.2.4', '2.2.5', '2.2.6', '2.2.7', '2.2.8', '2.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/06/GHSA-qm57-vhq3-3fwf/GHSA-qm57-vhq3-3fwf.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.1.0'}, {'fixed': '3.1.10'}]}], 'versions': ['3.1', '3.1.1', '3.1.2', '3.1.3', '3.1.4', '3.1.5', '3.1.6', '3.1.7', '3.1.8', '3.1.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/06/GHSA-qm57-vhq3-3fwf/GHSA-qm57-vhq3-3fwf.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2.0'}, {'fixed': '3.2.2'}]}], 'versions': ['3.2', '3.2.1'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/06/GHSA-qm57-vhq3-3fwf/GHSA-qm57-vhq3-3fwf.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N'}]},
            {'id': 'GHSA-rxjp-mfm9-w4wr', 'summary': 'Path Traversal in Django', 'details': 'In Django 2.2 before 2.2.21, 3.1 before 3.1.9, and 3.2 before 3.2.1, MultiPartParser, UploadedFile, and FieldFile allowed directory traversal via uploaded files with suitably crafted file names.', 'aliases': ['CVE-2021-31542'], 'modified': '2022-06-10T02:09:17.683292Z', 'published': '2021-06-04T21:15:56Z', 'database_specific': {'severity': 'HIGH', 'cwe_ids': ['CWE-22', 'CWE-434'], 'github_reviewed': True}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2021-31542'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/3.2/releases/security/'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://lists.debian.org/debian-lts-announce/2021/05/msg00005.html'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE/'}, {'type': 'WEB', 'url': 'https://security.netapp.com/advisory/ntap-20210618-0001/'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2021/may/04/security-releases/'}, {'type': 'WEB', 'url': 'http://www.openwall.com/lists/oss-security/2021/05/04/3'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '2.2.0'}, {'fixed': '2.2.21'}]}], 'versions': ['2.2', '2.2.1', '2.2.10', '2.2.11', '2.2.12', '2.2.13', '2.2.14', '2.2.15', '2.2.16', '2.2.17', '2.2.18', '2.2.19', '2.2.2', '2.2.20', '2.2.3', '2.2.4', '2.2.5', '2.2.6', '2.2.7', '2.2.8', '2.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/06/GHSA-rxjp-mfm9-w4wr/GHSA-rxjp-mfm9-w4wr.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.0.0'}, {'fixed': '3.1.9'}]}], 'versions': ['3.0', '3.0.1', '3.0.10', '3.0.11', '3.0.12', '3.0.13', '3.0.14', '3.0.2', '3.0.3', '3.0.4', '3.0.5', '3.0.6', '3.0.7', '3.0.8', '3.0.9', '3.1', '3.1.1', '3.1.2', '3.1.3', '3.1.4', '3.1.5', '3.1.6', '3.1.7', '3.1.8', '3.1a1', '3.1b1', '3.1rc1'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/06/GHSA-rxjp-mfm9-w4wr/GHSA-rxjp-mfm9-w4wr.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2.0'}, {'fixed': '3.2.1'}]}], 'versions': ['3.2'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/06/GHSA-rxjp-mfm9-w4wr/GHSA-rxjp-mfm9-w4wr.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N'}]},
            {'id': 'GHSA-v6rh-hp5x-86rv', 'summary': 'Potential bypass of an upstream access control based on URL paths in Django', 'details': 'In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths. This issue has low severity, according to the Django security policy.', 'aliases': ['CVE-2021-44420'], 'modified': '2022-06-10T02:16:01.543530Z', 'published': '2021-12-09T19:09:37Z', 'database_specific': {'cwe_ids': ['CWE-287'], 'severity': 'HIGH', 'github_reviewed': True}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2021-44420'}, {'type': 'WEB', 'url': 'https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/3.2/releases/security/'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/'}, {'type': 'WEB', 'url': 'https://security.netapp.com/advisory/ntap-20211229-0006/'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2021/dec/07/security-releases/'}, {'type': 'WEB', 'url': 'https://www.openwall.com/lists/oss-security/2021/12/07/1'}, {'type': 'PACKAGE', 'url': 'https://github.com/django/django'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '0'}, {'fixed': '2.2.25'}]}], 'versions': ['1.0.1', '1.0.2', '1.0.3', '1.0.4', '1.1', '1.1.1', '1.1.2', '1.1.3', '1.1.4', '1.10', '1.10.1', '1.10.2', '1.10.3', '1.10.4', '1.10.5', '1.10.6', '1.10.7', '1.10.8', '1.10a1', '1.10b1', '1.10rc1', '1.11', '1.11.1', '1.11.10', '1.11.11', '1.11.12', '1.11.13', '1.11.14', '1.11.15', '1.11.16', '1.11.17', '1.11.18', '1.11.2', '1.11.20', '1.11.21', '1.11.22', '1.11.23', '1.11.24', '1.11.25', '1.11.26', '1.11.27', '1.11.28', '1.11.29', '1.11.3', '1.11.4', '1.11.5', '1.11.6', '1.11.7', '1.11.8', '1.11.9', '1.11a1', '1.11b1', '1.11rc1', '1.2', '1.2.1', '1.2.2', '1.2.3', '1.2.4', '1.2.5', '1.2.6', '1.2.7', '1.3', '1.3.1', '1.3.2', '1.3.3', '1.3.4', '1.3.5', '1.3.6', '1.3.7', '1.4', '1.4.1', '1.4.10', '1.4.11', '1.4.12', '1.4.13', '1.4.14', '1.4.15', '1.4.16', '1.4.17', '1.4.18', '1.4.19', '1.4.2', '1.4.20', '1.4.21', '1.4.22', '1.4.3', '1.4.4', '1.4.5', '1.4.6', '1.4.7', '1.4.8', '1.4.9', '1.5', '1.5.1', '1.5.10', '1.5.11', '1.5.12', '1.5.2', '1.5.3', '1.5.4', '1.5.5', '1.5.6', '1.5.7', '1.5.8', '1.5.9', '1.6', '1.6.1', '1.6.10', '1.6.11', '1.6.2', '1.6.3', '1.6.4', '1.6.5', '1.6.6', '1.6.7', '1.6.8', '1.6.9', '1.7', '1.7.1', '1.7.10', '1.7.11', '1.7.2', '1.7.3', '1.7.4', '1.7.5', '1.7.6', '1.7.7', '1.7.8', '1.7.9', '1.8', '1.8.1', '1.8.10', '1.8.11', '1.8.12', '1.8.13', '1.8.14', '1.8.15', '1.8.16', '1.8.17', '1.8.18', '1.8.19', '1.8.2', '1.8.3', '1.8.4', '1.8.5', '1.8.6', '1.8.7', '1.8.8', '1.8.9', '1.8a1', '1.8b1', '1.8b2', '1.8c1', '1.9', '1.9.1', '1.9.10', '1.9.11', '1.9.12', '1.9.13', '1.9.2', '1.9.3', '1.9.4', '1.9.5', '1.9.6', '1.9.7', '1.9.8', '1.9.9', '1.9a1', '1.9b1', '1.9rc1', '1.9rc2', '2.0', '2.0.1', '2.0.10', '2.0.12', '2.0.13', '2.0.2', '2.0.3', '2.0.4', '2.0.5', '2.0.6', '2.0.7', '2.0.8', '2.0.9', '2.0a1', '2.0b1', '2.0rc1', '2.1', '2.1.1', '2.1.10', '2.1.11', '2.1.12', '2.1.13', '2.1.14', '2.1.15', '2.1.2', '2.1.3', '2.1.4', '2.1.5', '2.1.7', '2.1.8', '2.1.9', '2.1a1', '2.1b1', '2.1rc1', '2.2', '2.2.1', '2.2.10', '2.2.11', '2.2.12', '2.2.13', '2.2.14', '2.2.15', '2.2.16', '2.2.17', '2.2.18', '2.2.19', '2.2.2', '2.2.20', '2.2.21', '2.2.22', '2.2.23', '2.2.24', '2.2.3', '2.2.4', '2.2.5', '2.2.6', '2.2.7', '2.2.8', '2.2.9', '2.2a1', '2.2b1', '2.2rc1'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/12/GHSA-v6rh-hp5x-86rv/GHSA-v6rh-hp5x-86rv.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.0'}, {'fixed': '3.1.14'}]}], 'versions': ['3.0', '3.0.1', '3.0.10', '3.0.11', '3.0.12', '3.0.13', '3.0.14', '3.0.2', '3.0.3', '3.0.4', '3.0.5', '3.0.6', '3.0.7', '3.0.8', '3.0.9', '3.1', '3.1.1', '3.1.10', '3.1.11', '3.1.12', '3.1.13', '3.1.2', '3.1.3', '3.1.4', '3.1.5', '3.1.6', '3.1.7', '3.1.8', '3.1.9', '3.1a1', '3.1b1', '3.1rc1'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/12/GHSA-v6rh-hp5x-86rv/GHSA-v6rh-hp5x-86rv.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2'}, {'fixed': '3.2.10'}]}], 'versions': ['3.2', '3.2.1', '3.2.2', '3.2.3', '3.2.4', '3.2.5', '3.2.6', '3.2.7', '3.2.8', '3.2.9'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/12/GHSA-v6rh-hp5x-86rv/GHSA-v6rh-hp5x-86rv.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L'}]},
            {'id': 'GHSA-w24h-v9qh-8gxj', 'summary': 'SQL Injection in Django', 'details': 'A SQL injection issue was discovered in QuerySet.explain() in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. This occurs by passing a crafted dictionary (with dictionary expansion) as the **options argument, and placing the injection payload in an option name.', 'aliases': ['CVE-2022-28347'], 'modified': '2022-06-10T02:12:16.140612Z', 'published': '2022-04-13T00:00:33Z', 'database_specific': {'github_reviewed': True, 'severity': 'CRITICAL', 'cwe_ids': ['CWE-89']}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2022-28347'}, {'type': 'WEB', 'url': 'https://github.com/django/django/commit/6723a26e59b0b5429a0c5873941e01a2e1bdbb81'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/4.0/releases/security/'}, {'type': 'ADVISORY', 'url': 'https://github.com/advisories/GHSA-w24h-v9qh-8gxj'}, {'type': 'WEB', 'url': 'https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-191.yaml'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2022/apr/11/security-releases/'}, {'type': 'WEB', 'url': 'http://www.openwall.com/lists/oss-security/2022/04/11/1'}, {'type': 'PACKAGE', 'url': 'https://github.com/django/django'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '2.2'}, {'fixed': '2.2.28'}]}], 'versions': ['2.2', '2.2.1', '2.2.10', '2.2.11', '2.2.12', '2.2.13', '2.2.14', '2.2.15', '2.2.16', '2.2.17', '2.2.18', '2.2.19', '2.2.2', '2.2.20', '2.2.21', '2.2.22', '2.2.23', '2.2.24', '2.2.25', '2.2.26', '2.2.27', '2.2.3', '2.2.4', '2.2.5', '2.2.6', '2.2.7', '2.2.8', '2.2.9'], 'ecosystem_specific': {'affected_functions': ['django.db.models.QuerySet.explain']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/04/GHSA-w24h-v9qh-8gxj/GHSA-w24h-v9qh-8gxj.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2'}, {'fixed': '3.2.13'}]}], 'versions': ['3.2', '3.2.1', '3.2.10', '3.2.11', '3.2.12', '3.2.2', '3.2.3', '3.2.4', '3.2.5', '3.2.6', '3.2.7', '3.2.8', '3.2.9'], 'ecosystem_specific': {'affected_functions': ['django.db.models.QuerySet.explain']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/04/GHSA-w24h-v9qh-8gxj/GHSA-w24h-v9qh-8gxj.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '4.0'}, {'fixed': '4.0.4'}]}], 'versions': ['4.0', '4.0.1', '4.0.2', '4.0.3'], 'ecosystem_specific': {'affected_functions': ['django.db.models.QuerySet.explain']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/04/GHSA-w24h-v9qh-8gxj/GHSA-w24h-v9qh-8gxj.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'}]},
            {'id': 'GHSA-xpfp-f569-q3p2', 'summary': 'SQL Injection in Django', 'details': 'Django 3.1.x before 3.1.13 and 3.2.x before 3.2.5 allows QuerySet.order_by SQL injection if order_by is untrusted input from a client of a web application.', 'aliases': ['CVE-2021-35042'], 'modified': '2022-06-10T02:16:18.361165Z', 'published': '2021-09-22T17:34:49Z', 'database_specific': {'cwe_ids': ['CWE-89'], 'severity': 'CRITICAL', 'github_reviewed': True}, 'references': [{'type': 'ADVISORY', 'url': 'https://nvd.nist.gov/vuln/detail/CVE-2021-35042'}, {'type': 'WEB', 'url': 'https://github.com/django/django/commit/0bd57a879a0d54920bb9038a732645fb917040e9'}, {'type': 'WEB', 'url': 'https://docs.djangoproject.com/en/3.2/releases/security/'}, {'type': 'WEB', 'url': 'https://groups.google.com/forum/#!forum/django-announce'}, {'type': 'WEB', 'url': 'https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SS6NJTBYWOX6J7G4U3LUOILARJKWPQ5Y/'}, {'type': 'WEB', 'url': 'https://security.netapp.com/advisory/ntap-20210805-0008/'}, {'type': 'WEB', 'url': 'https://www.djangoproject.com/weblog/2021/jul/01/security-releases/'}, {'type': 'WEB', 'url': 'https://www.openwall.com/lists/oss-security/2021/07/02/2'}, {'type': 'PACKAGE', 'url': 'https://github.com/django/django'}], 'affected': [{'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.2.0'}, {'fixed': '3.2.5'}]}], 'versions': ['3.2', '3.2.1', '3.2.2', '3.2.3', '3.2.4'], 'ecosystem_specific': {'affected_functions': ['django.db.models.query.QuerySet.order_by']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/09/GHSA-xpfp-f569-q3p2/GHSA-xpfp-f569-q3p2.json'}}, {'package': {'name': 'Django', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/Django'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '3.0.0'}, {'fixed': '3.1.13'}]}], 'versions': ['3.0', '3.0.1', '3.0.10', '3.0.11', '3.0.12', '3.0.13', '3.0.14', '3.0.2', '3.0.3', '3.0.4', '3.0.5', '3.0.6', '3.0.7', '3.0.8', '3.0.9', '3.1', '3.1.1', '3.1.10', '3.1.11', '3.1.12', '3.1.2', '3.1.3', '3.1.4', '3.1.5', '3.1.6', '3.1.7', '3.1.8', '3.1.9', '3.1a1', '3.1b1', '3.1rc1'], 'ecosystem_specific': {'affected_functions': ['django.db.models.query.QuerySet.order_by']}, 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/09/GHSA-xpfp-f569-q3p2/GHSA-xpfp-f569-q3p2.json'}}], 'schema_version': '1.2.0', 'severity': [{'type': 'CVSS_V3', 'score': 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'}]}
        ]
    }

# fmt: on
@pytest.fixture(scope = "session")
def main_django_expected():
    # fmt: off
    return [
        ('GHSA-2gwj-7jmv-h26r', 'An issue was discovered in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. QuerySet.annotate(), aggregate(), and extra() methods are subject to SQL injection in column aliases via a crafted dictionary (with dictionary expansion) as the passed **kwargs.'),
        ('GHSA-53qw-q765-4fww', 'An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.'),
        ('GHSA-8c5j-9r9f-c6w8', "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. Due to leveraging the Django Template Language's variable resolution logic, the dictsort template filter was potentially vulnerable to information disclosure, or an unintended method call, if passed a suitably crafted key."),
        ('GHSA-jrh2-hc4r-7jwx', 'Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it.'),
        ('GHSA-qm57-vhq3-3fwf', 'In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers.'),
        ('GHSA-rxjp-mfm9-w4wr', 'In Django 2.2 before 2.2.21, 3.1 before 3.1.9, and 3.2 before 3.2.1, MultiPartParser, UploadedFile, and FieldFile allowed directory traversal via uploaded files with suitably crafted file names.'),
        ('GHSA-v6rh-hp5x-86rv', 'In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths. This issue has low severity, according to the Django security policy.'),
        ('GHSA-w24h-v9qh-8gxj', 'A SQL injection issue was discovered in QuerySet.explain() in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. This occurs by passing a crafted dictionary (with dictionary expansion) as the **options argument, and placing the injection payload in an option name.'),
        ('GHSA-xpfp-f569-q3p2', 'Django 3.1.x before 3.1.13 and 3.2.x before 3.2.5 allows QuerySet.order_by SQL injection if order_by is untrusted input from a client of a web application.')
    ]
